/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1McpRouteImport } from './routes/v1/mcp'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiPublicSlugRouteImport } from './routes/api/public/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppTimelineRouteImport } from './routes/_auth/app/timeline'
import { Route as AuthAppShortcutsRouteImport } from './routes/_auth/app/shortcuts'
import { Route as AuthAppProfileRouteImport } from './routes/_auth/app/profile'
import { Route as AuthAppLearningRouteImport } from './routes/_auth/app/learning'
import { Route as AuthAppFocusRouteImport } from './routes/_auth/app/focus'
import { Route as AuthAppAboutRouteImport } from './routes/_auth/app/about'
import { Route as ApiMcpV1TasksRouteImport } from './routes/api/mcp/v1/tasks'
import { Route as ApiMcpV1SpacesRouteImport } from './routes/api/mcp/v1/spaces'
import { Route as ApiMcpV1MeRouteImport } from './routes/api/mcp/v1/me'
import { Route as ApiIntegrationsNotionConnectRouteImport } from './routes/api/integrations/notion/connect'
import { Route as ApiIntegrationsNotionCallbackRouteImport } from './routes/api/integrations/notion/callback'
import { Route as AuthAppTasksTaskIdRouteImport } from './routes/_auth/app/tasks.$taskId'
import { Route as ApiMcpV1TasksTaskIdRouteImport } from './routes/api/mcp/v1/tasks/$taskId'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1McpRoute = V1McpRouteImport.update({
  id: '/v1/mcp',
  path: '/v1/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiPublicSlugRoute = ApiPublicSlugRouteImport.update({
  id: '/api/public/$slug',
  path: '/api/public/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppTimelineRoute = AuthAppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppShortcutsRoute = AuthAppShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProfileRoute = AuthAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppLearningRoute = AuthAppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppFocusRoute = AuthAppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppAboutRoute = AuthAppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiMcpV1TasksRoute = ApiMcpV1TasksRouteImport.update({
  id: '/api/mcp/v1/tasks',
  path: '/api/mcp/v1/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpV1SpacesRoute = ApiMcpV1SpacesRouteImport.update({
  id: '/api/mcp/v1/spaces',
  path: '/api/mcp/v1/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpV1MeRoute = ApiMcpV1MeRouteImport.update({
  id: '/api/mcp/v1/me',
  path: '/api/mcp/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsNotionConnectRoute =
  ApiIntegrationsNotionConnectRouteImport.update({
    id: '/api/integrations/notion/connect',
    path: '/api/integrations/notion/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsNotionCallbackRoute =
  ApiIntegrationsNotionCallbackRouteImport.update({
    id: '/api/integrations/notion/callback',
    path: '/api/integrations/notion/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAppTasksTaskIdRoute = AuthAppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiMcpV1TasksTaskIdRoute = ApiMcpV1TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiMcpV1TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/p/$slug': typeof PSlugRoute
  '/v1/mcp': typeof V1McpRoute
  '/app/about': typeof AuthAppAboutRoute
  '/app/focus': typeof AuthAppFocusRoute
  '/app/learning': typeof AuthAppLearningRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/shortcuts': typeof AuthAppShortcutsRoute
  '/app/timeline': typeof AuthAppTimelineRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$slug': typeof ApiPublicSlugRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/tasks/$taskId': typeof AuthAppTasksTaskIdRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/integrations/notion/connect': typeof ApiIntegrationsNotionConnectRoute
  '/api/mcp/v1/me': typeof ApiMcpV1MeRoute
  '/api/mcp/v1/spaces': typeof ApiMcpV1SpacesRoute
  '/api/mcp/v1/tasks': typeof ApiMcpV1TasksRouteWithChildren
  '/api/mcp/v1/tasks/$taskId': typeof ApiMcpV1TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/p/$slug': typeof PSlugRoute
  '/v1/mcp': typeof V1McpRoute
  '/app/about': typeof AuthAppAboutRoute
  '/app/focus': typeof AuthAppFocusRoute
  '/app/learning': typeof AuthAppLearningRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/shortcuts': typeof AuthAppShortcutsRoute
  '/app/timeline': typeof AuthAppTimelineRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$slug': typeof ApiPublicSlugRoute
  '/app': typeof AuthAppIndexRoute
  '/app/tasks/$taskId': typeof AuthAppTasksTaskIdRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/integrations/notion/connect': typeof ApiIntegrationsNotionConnectRoute
  '/api/mcp/v1/me': typeof ApiMcpV1MeRoute
  '/api/mcp/v1/spaces': typeof ApiMcpV1SpacesRoute
  '/api/mcp/v1/tasks': typeof ApiMcpV1TasksRouteWithChildren
  '/api/mcp/v1/tasks/$taskId': typeof ApiMcpV1TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/p/$slug': typeof PSlugRoute
  '/v1/mcp': typeof V1McpRoute
  '/_auth/app/about': typeof AuthAppAboutRoute
  '/_auth/app/focus': typeof AuthAppFocusRoute
  '/_auth/app/learning': typeof AuthAppLearningRoute
  '/_auth/app/profile': typeof AuthAppProfileRoute
  '/_auth/app/shortcuts': typeof AuthAppShortcutsRoute
  '/_auth/app/timeline': typeof AuthAppTimelineRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$slug': typeof ApiPublicSlugRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/tasks/$taskId': typeof AuthAppTasksTaskIdRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/integrations/notion/connect': typeof ApiIntegrationsNotionConnectRoute
  '/api/mcp/v1/me': typeof ApiMcpV1MeRoute
  '/api/mcp/v1/spaces': typeof ApiMcpV1SpacesRoute
  '/api/mcp/v1/tasks': typeof ApiMcpV1TasksRouteWithChildren
  '/api/mcp/v1/tasks/$taskId': typeof ApiMcpV1TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/p/$slug'
    | '/v1/mcp'
    | '/app/about'
    | '/app/focus'
    | '/app/learning'
    | '/app/profile'
    | '/app/shortcuts'
    | '/app/timeline'
    | '/api/auth/$'
    | '/api/public/$slug'
    | '/app/'
    | '/app/tasks/$taskId'
    | '/api/integrations/notion/callback'
    | '/api/integrations/notion/connect'
    | '/api/mcp/v1/me'
    | '/api/mcp/v1/spaces'
    | '/api/mcp/v1/tasks'
    | '/api/mcp/v1/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/p/$slug'
    | '/v1/mcp'
    | '/app/about'
    | '/app/focus'
    | '/app/learning'
    | '/app/profile'
    | '/app/shortcuts'
    | '/app/timeline'
    | '/api/auth/$'
    | '/api/public/$slug'
    | '/app'
    | '/app/tasks/$taskId'
    | '/api/integrations/notion/callback'
    | '/api/integrations/notion/connect'
    | '/api/mcp/v1/me'
    | '/api/mcp/v1/spaces'
    | '/api/mcp/v1/tasks'
    | '/api/mcp/v1/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/p/$slug'
    | '/v1/mcp'
    | '/_auth/app/about'
    | '/_auth/app/focus'
    | '/_auth/app/learning'
    | '/_auth/app/profile'
    | '/_auth/app/shortcuts'
    | '/_auth/app/timeline'
    | '/api/auth/$'
    | '/api/public/$slug'
    | '/_auth/app/'
    | '/_auth/app/tasks/$taskId'
    | '/api/integrations/notion/callback'
    | '/api/integrations/notion/connect'
    | '/api/mcp/v1/me'
    | '/api/mcp/v1/spaces'
    | '/api/mcp/v1/tasks'
    | '/api/mcp/v1/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  PSlugRoute: typeof PSlugRoute
  V1McpRoute: typeof V1McpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicSlugRoute: typeof ApiPublicSlugRoute
  ApiIntegrationsNotionCallbackRoute: typeof ApiIntegrationsNotionCallbackRoute
  ApiIntegrationsNotionConnectRoute: typeof ApiIntegrationsNotionConnectRoute
  ApiMcpV1MeRoute: typeof ApiMcpV1MeRoute
  ApiMcpV1SpacesRoute: typeof ApiMcpV1SpacesRoute
  ApiMcpV1TasksRoute: typeof ApiMcpV1TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/mcp': {
      id: '/v1/mcp'
      path: '/v1/mcp'
      fullPath: '/v1/mcp'
      preLoaderRoute: typeof V1McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/public/$slug': {
      id: '/api/public/$slug'
      path: '/api/public/$slug'
      fullPath: '/api/public/$slug'
      preLoaderRoute: typeof ApiPublicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/timeline': {
      id: '/_auth/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AuthAppTimelineRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/shortcuts': {
      id: '/_auth/app/shortcuts'
      path: '/shortcuts'
      fullPath: '/app/shortcuts'
      preLoaderRoute: typeof AuthAppShortcutsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/profile': {
      id: '/_auth/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthAppProfileRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/learning': {
      id: '/_auth/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AuthAppLearningRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/focus': {
      id: '/_auth/app/focus'
      path: '/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AuthAppFocusRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/about': {
      id: '/_auth/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AuthAppAboutRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/mcp/v1/tasks': {
      id: '/api/mcp/v1/tasks'
      path: '/api/mcp/v1/tasks'
      fullPath: '/api/mcp/v1/tasks'
      preLoaderRoute: typeof ApiMcpV1TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/v1/spaces': {
      id: '/api/mcp/v1/spaces'
      path: '/api/mcp/v1/spaces'
      fullPath: '/api/mcp/v1/spaces'
      preLoaderRoute: typeof ApiMcpV1SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/v1/me': {
      id: '/api/mcp/v1/me'
      path: '/api/mcp/v1/me'
      fullPath: '/api/mcp/v1/me'
      preLoaderRoute: typeof ApiMcpV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/notion/connect': {
      id: '/api/integrations/notion/connect'
      path: '/api/integrations/notion/connect'
      fullPath: '/api/integrations/notion/connect'
      preLoaderRoute: typeof ApiIntegrationsNotionConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/notion/callback': {
      id: '/api/integrations/notion/callback'
      path: '/api/integrations/notion/callback'
      fullPath: '/api/integrations/notion/callback'
      preLoaderRoute: typeof ApiIntegrationsNotionCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/tasks/$taskId': {
      id: '/_auth/app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AuthAppTasksTaskIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/mcp/v1/tasks/$taskId': {
      id: '/api/mcp/v1/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/mcp/v1/tasks/$taskId'
      preLoaderRoute: typeof ApiMcpV1TasksTaskIdRouteImport
      parentRoute: typeof ApiMcpV1TasksRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppAboutRoute: typeof AuthAppAboutRoute
  AuthAppFocusRoute: typeof AuthAppFocusRoute
  AuthAppLearningRoute: typeof AuthAppLearningRoute
  AuthAppProfileRoute: typeof AuthAppProfileRoute
  AuthAppShortcutsRoute: typeof AuthAppShortcutsRoute
  AuthAppTimelineRoute: typeof AuthAppTimelineRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppTasksTaskIdRoute: typeof AuthAppTasksTaskIdRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppAboutRoute: AuthAppAboutRoute,
  AuthAppFocusRoute: AuthAppFocusRoute,
  AuthAppLearningRoute: AuthAppLearningRoute,
  AuthAppProfileRoute: AuthAppProfileRoute,
  AuthAppShortcutsRoute: AuthAppShortcutsRoute,
  AuthAppTimelineRoute: AuthAppTimelineRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppTasksTaskIdRoute: AuthAppTasksTaskIdRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ApiMcpV1TasksRouteChildren {
  ApiMcpV1TasksTaskIdRoute: typeof ApiMcpV1TasksTaskIdRoute
}

const ApiMcpV1TasksRouteChildren: ApiMcpV1TasksRouteChildren = {
  ApiMcpV1TasksTaskIdRoute: ApiMcpV1TasksTaskIdRoute,
}

const ApiMcpV1TasksRouteWithChildren = ApiMcpV1TasksRoute._addFileChildren(
  ApiMcpV1TasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  PSlugRoute: PSlugRoute,
  V1McpRoute: V1McpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicSlugRoute: ApiPublicSlugRoute,
  ApiIntegrationsNotionCallbackRoute: ApiIntegrationsNotionCallbackRoute,
  ApiIntegrationsNotionConnectRoute: ApiIntegrationsNotionConnectRoute,
  ApiMcpV1MeRoute: ApiMcpV1MeRoute,
  ApiMcpV1SpacesRoute: ApiMcpV1SpacesRoute,
  ApiMcpV1TasksRoute: ApiMcpV1TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
